baseurl = "https://www.rdhox.io" # Hostname (and path) to the root.
title = "${rdhox}" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-us" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "monokai" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "rdhox-io" # Enable or disable Disqus

[params] # theme parameters
    author = "rdhox" # Author's name.
    info = "Jamstack believer - Front-end & serverless tech." # Author's job title or info.
    description = "Welcome to my personnal website! You'll find here some informations about my work and some articles on my blog. Don't hesitate to contact me or follow me on twitter if you wish!" # Site description.
    keywords = "blog,developer,personal,javascript,node,react,serverless,aws,freelance" # Site keywords.
    avatar = true # display an avatar.
    avatarurl = "images/avatar.jpg" # if avatar = true, must contain the path of the avatar in the static folder. 

    disqusShortname = "rdhox-io" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Add footer content
    footercontent = "contact@rdhox.io"

    # Custom CSS
    custom_css = ["css/custom.css"]

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/rdhox/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/rd_hox/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"