baseurl = "https://rdhox.io" # Hostname (and path) to the root.
title = "${rdhox}" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en-us" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "native" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "rdhox-io" # Enable or disable Disqus
googleAnalytics = "UA-121695487-1"

[params] # theme parameters
    author = "rdhox - Freelancer" # Author's name.
    info = "Front-end UI and Mobile Developer" # Author's job title or info.
    description = "Welcome to my personnal website! You'll find here some informations about my work and some articles on my blog. Don't hesitate to contact me or follow me on twitter if you wish!" # Site description.
    keywords = "blog,developer,personal,javascript,node,react,serverless,aws,freelance" # Site keywords.
    # avatarurl = "images/avatar.jpg" # if avatar = true, must contain the path of the avatar in the static folder. 
    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Add footer content
    footercontent = "contact(at)rdhox.io"

    # Custom CSS

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/rdhox/"
    icon = "fab fa-github"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/rd_hox/"
    icon = "fab fa-twitter"
[[params.social]]
    name = "Linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/renauddechaux"
    icon = "fab fa-linkedin"
[[params.social]]
    name = "RSS"
    weight = 4
    url = "https://rdhox.io/index.xml/"
    icon = "fa fa-rss-square"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"